name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 17.6.0

      - name: List Versions
        run: |
          node --version
          npm --version

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests & Lint
        run: |
          npm test
          npm run lint
